# Generated by Django 2.2.3 on 2019-08-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='album',
        ),
        migrations.DeleteModel(
            name='Image2',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
