# Generated by Django 2.2.3 on 2019-08-03 14:07

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20190802_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=album.models.image_path),
        ),
    ]
