# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180212_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageList2', to='album.Album')),
            ],
        ),
    ]
