# Generated by Django 2.2.3 on 2019-08-05 13:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20190803_1407'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
