# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='image2',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
