# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
