# Generated by Django 2.2.3 on 2019-08-05 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_a_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b',
            name='rel2a',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.A'),
        ),
    ]
