# Generated by Django 2.2.3 on 2019-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20190805_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_group',
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
