# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album'),
        ),
    ]
