# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-08 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_test_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image2',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
