# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material2MaterialList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogWeb.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('materials', models.ManyToManyField(blank=True, through='catalogWeb.Material2MaterialList', to='catalogWeb.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('provenance', models.CharField(max_length=45)),
                ('dimensions', models.CharField(max_length=45)),
                ('technique', models.CharField(max_length=45)),
                ('materialList', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.MaterialList')),
            ],
        ),
        migrations.CreateModel(
            name='Monument2Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfield', models.CharField(max_length=45)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Monument')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('garant', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('realized_by', models.CharField(max_length=45)),
                ('realized_for', models.CharField(max_length=45)),
                ('monumentList', models.ManyToManyField(blank=True, through='catalogWeb.Monument2Project', to='catalogWeb.Monument')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('UVA', models.BooleanField()),
                ('UVC', models.BooleanField()),
                ('RUVA', models.BooleanField()),
                ('IR', models.BooleanField()),
                ('RTG', models.BooleanField()),
                ('CT', models.BooleanField()),
                ('ch_t_research', models.BooleanField()),
                ('sondazny', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('monument2ProjectRelation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Project')),
                ('projectRelation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Monument2Project')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('monument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogWeb.Monument')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Project')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Research')),
            ],
        ),
        migrations.CreateModel(
            name='Restorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='researchList',
            field=models.ManyToManyField(blank=True, to='catalogWeb.Research'),
        ),
        migrations.AddField(
            model_name='project',
            name='restorerList',
            field=models.ManyToManyField(blank=True, to='catalogWeb.Restorer'),
        ),
        migrations.AddField(
            model_name='monument2project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Project'),
        ),
        migrations.AddField(
            model_name='material2materiallist',
            name='materialList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.MaterialList'),
        ),
    ]
