# Generated by Django 2.2.3 on 2019-07-29 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('author', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('placement', models.CharField(blank=True, max_length=45, null=True)),
                ('provenance', models.CharField(max_length=45)),
                ('owner', models.CharField(blank=True, max_length=45, null=True)),
                ('dimensions', models.CharField(max_length=45)),
                ('technique', models.CharField(max_length=45)),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monument2Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfield', models.CharField(max_length=45)),
                ('monument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Monument')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
                ('person2user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('realized_by', models.CharField(max_length=45)),
                ('realized_for', models.CharField(max_length=45)),
                ('garant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='garant_for', to='catalogWeb.Person')),
                ('monument_list', models.ManyToManyField(blank=True, through='catalogWeb.Monument2Project', to='catalogWeb.Monument')),
                ('restorerList', models.ManyToManyField(blank=True, to='catalogWeb.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('UVA', models.BooleanField()),
                ('UVC', models.BooleanField()),
                ('RUVA', models.BooleanField()),
                ('IR', models.BooleanField()),
                ('RTG', models.BooleanField()),
                ('CT', models.BooleanField()),
                ('CT_date', models.DateField(blank=True, null=True)),
                ('CT_description', models.TextField(blank=True, null=True)),
                ('ch_t_research', models.BooleanField()),
                ('sondazny', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
                ('monument', models.ManyToManyField(blank=True, to='catalogWeb.Monument')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('monument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogWeb.Monument')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Project')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Research')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(to='catalogWeb.Role'),
        ),
        migrations.AddField(
            model_name='monument2project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Project'),
        ),
        migrations.CreateModel(
            name='Monument2Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogWeb.Material')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Monument')),
            ],
        ),
        migrations.AddField(
            model_name='monument',
            name='materials',
            field=models.ManyToManyField(blank=True, through='catalogWeb.Monument2Material', to='catalogWeb.Material'),
        ),
        migrations.AddField(
            model_name='monument',
            name='related_monuments',
            field=models.ManyToManyField(blank=True, to='catalogWeb.Monument'),
        ),
    ]
