# Generated by Django 2.2.3 on 2019-08-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20190805_1308'),
        ('catalogWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='related_monuments',
        ),
        migrations.AddField(
            model_name='monument',
            name='album_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_1_rel', to='album.Album'),
        ),
        migrations.AddField(
            model_name='monument',
            name='album_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_2_rel', to='album.Album'),
        ),
        migrations.AddField(
            model_name='monument',
            name='parent_monument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogWeb.Monument'),
        ),
    ]
