# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('garant', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('realized_by', models.CharField(max_length=45)),
                ('realized_for', models.CharField(max_length=45)),
                ('restorers', models.ManyToManyField(to='catalogWeb.Restorer')),
            ],
        ),
    ]
