# Generated by Django 2.0.1 on 2018-01-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='projectRelation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Monument2Project'),
        ),
        migrations.AlterField(
            model_name='research',
            name='monument2ProjectRelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Project'),
        ),
    ]
