# Generated by Django 2.2.3 on 2019-08-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0002_auto_20190805_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='album_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_1_rel', to='album.Album'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='album_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_2_rel', to='album.Album'),
        ),
    ]
