# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('provenance', models.CharField(max_length=45)),
                ('dimensions', models.CharField(max_length=45)),
                ('technique', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restorer',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(default=int, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restorer',
            name='restorer_id',
            field=models.IntegerField(default=int, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
