# Generated by Django 2.0.1 on 2018-01-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0002_auto_20180126_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='projectRelation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Monument2Project'),
            preserve_default=False,
        ),
    ]
