# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0003_remove_materiallist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='researchList',
        ),
        migrations.AddField(
            model_name='research',
            name='monument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogWeb.Monument'),
        ),
        migrations.AlterField(
            model_name='research',
            name='projectRelation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalogWeb.Monument2Project'),
        ),
    ]
