# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0003_auto_20171017_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='objects',
            field=models.ManyToManyField(to='catalogWeb.Object'),
        ),
    ]
