# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0004_auto_20180324_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
