# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0005_auto_20180324_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='catalogWeb.Project'),
        ),
    ]
