# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0005_remove_research_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='monument2ProjectRelation',
        ),
        migrations.RemoveField(
            model_name='research',
            name='projectRelation',
        ),
        migrations.AddField(
            model_name='research',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Project'),
        ),
    ]
