# Generated by Django 2.2.3 on 2019-08-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0005_auto_20190805_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='album',
        ),
        migrations.RemoveField(
            model_name='research',
            name='album',
        ),
    ]
