# Generated by Django 2.2.3 on 2019-08-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20190805_2003'),
        ('catalogWeb', '0006_auto_20190805_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='album_1',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='album_2',
        ),
        migrations.AddField(
            model_name='monument',
            name='album_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_2_rel', to='album.Album'),
        ),
        migrations.AddField(
            model_name='monument',
            name='album_pre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_1_rel', to='album.Album'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.Album'),
        ),
        migrations.AlterField(
            model_name='person',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.Album'),
        ),
    ]
