# Generated by Django 2.2.3 on 2019-08-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0007_auto_20190807_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monument',
            old_name='album_post',
            new_name='album_after',
        ),
        migrations.RenameField(
            model_name='monument',
            old_name='album_pre',
            new_name='album_before',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='album',
        ),
    ]
