# Generated by Django 2.2.3 on 2019-08-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0008_auto_20190807_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('pl', 'Planning in progress'), ('on', 'Work in progress'), ('fi', 'Work finished')], default='pl', max_length=2),
        ),
    ]
