# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0008_auto_20180202_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument2project',
            name='monument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Monument'),
        ),
    ]
