# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0009_auto_20180202_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monument2Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogWeb.Material')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogWeb.Monument')),
            ],
        ),
        migrations.AddField(
            model_name='monument',
            name='materials',
            field=models.ManyToManyField(blank=True, through='catalogWeb.Monument2Material', to='catalogWeb.Material'),
        ),
    ]
