# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0010_auto_20180401_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='author',
            field=models.CharField(default=None, max_length=45, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monument',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
