# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0010_auto_20180202_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material2materiallist',
            name='material',
        ),
        migrations.RemoveField(
            model_name='material2materiallist',
            name='materialList',
        ),
        migrations.RemoveField(
            model_name='materiallist',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='materialList',
        ),
        migrations.DeleteModel(
            name='Material2MaterialList',
        ),
        migrations.DeleteModel(
            name='MaterialList',
        ),
    ]
