# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogWeb', '0011_auto_20180401_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='author',
        ),
        migrations.AlterField(
            model_name='monument',
            name='date',
            field=models.DateField(),
        ),
    ]
